name: Docker Runner

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Stop docker compose
        run: docker-compose -f /opt/discord-compose.yml down
        
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
        
      - name: Build Container
        run: docker-compose -f /opt/discord-compose.yml build --no-cache

      - name: Start up docker compose
        run: docker-compose -f /opt/discord-compose.yml up -d
        
      - name: Cleanup Unused Images
        run: docker image prune -f
