name: Docker Runner

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Get directory
        run: ls -la
        
      - uses: actions/checkout@v3

      - name: Run Container
        run: docker-compose -f /opt/discord-compose.yml up -d --build

#      - name: Cleanup Unused Images
#        run: docker image prune -f
