name: Docker Runner

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Stop other docker compose
        run: docker-compose -f /opt/bingo_bot/discord-compose.yml down
        
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          path: /opt/bingo_bot

      - name: Copy local files
        run: |
          cp /opt/bingo_bot/config.py . &&
          cp /opt/bingo_bot/token.json . &&
          cp /opt/bingo_bot/credentials.json .
        
      - name: Build Container
        run: docker-compose -f /opt/bingo_bot/discord-compose.yml build --no-cache

      - name: Start up docker compose
        run: docker-compose -f /opt/bingo_bot/discord-compose.yml up -d
        
      - name: Cleanup Unused Images
        run: docker image prune -f
