name: Docker Runner

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Stop docker compose
        run: docker-compose -f /opt/discord-compose.yml down
        
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Run Container
        run: docker-compose -f /opt/discord-compose.yml up -d --build

      - name: Sync Bot Commands
        run: |
          cd /opt/appdata/discord-bots/ && \
          docker exec -it opt_osrs-bingo-bot_1 bash && \
          python3 bot.py && \
          sleep 10 && \
          exit

      - name: Cleanup Unused Images
        run: docker image prune -f
